### ISSUE TITLE
release v1.0.0

### ISSUE THREAD

**Issue by rursprung** [rust-embedded-community/adafruit-bluefruit-protocol-rs#25]
pre-requisites:
* https://github.com/knurling-rs/defmt/issues/795
* https://github.com/kornelski/rust-rgb/issues/39
* ensure that we fulfill everything from [the API checklist](https://rust-lang.github.io/api-guidelines/checklist.html), at least these seem to be wrong or at least need to be double-checked:
  * [x] Feature names are free of placeholder words ([C-FEATURE](https://rust-lang.github.io/api-guidelines/naming.html#c-feature)): we currently have `use-alloc` and `use-heapless` - we need to drop the `use-` prefix
  * [x] Types eagerly implement common traits ([C-COMMON-TRAITS](https://rust-lang.github.io/api-guidelines/interoperability.html#c-common-traits)) - to be double-checked
  * [x] Error types are meaningful and well-behaved ([C-GOOD-ERR](https://rust-lang.github.io/api-guidelines/interoperability.html#c-good-err)) - should probably be implemented for `std` environments?
  * [x] Crate level docs are thorough and include examples ([C-CRATE-DOC](https://rust-lang.github.io/api-guidelines/documentation.html#c-crate-doc)) - missing explicit example for calling the library directly in the rustdoc & readme
  * [ ] Public dependencies of a stable crate are stable ([C-STABLE](https://rust-lang.github.io/api-guidelines/necessities.html#c-stable)) - see dependency list above, they're all at 0.x 🙁

**Comment by rursprung** [comment]
update: the `heapless` dependency is now gone since #38 and the same is true for the `use-[alloc|heapless]` features (and other things have been fixed as well)

**Comment by jannic** [comment]
@rursprung did the release! :tada:
